# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detection', models.CharField(choices=[('FACE_DETECTION', 'FACE_DETECTION'), ('LANDMARK_DETECTION', 'LANDMARK_DETECTION'), ('LOGO_DETECTION', 'LOGO_DETECTION'), ('LABEL_DETECTION', 'LABEL_DETECTION'), ('TEXT_DETECTION', 'TEXT_DETECTION'), ('SAGE_SEARCH_DETECTION', 'SAFE_SEARCH_DETECTION'), ('IMAGE_PROPERTIES', 'IMAGE_PROPERTIES')], default='LABEL_DETECTION', max_length=32)),
                ('maxResult', models.IntegerField()),
                ('result', models.TextField()),
                ('data', models.ImageField(upload_to='images')),
            ],
        ),
    ]
