# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 07:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='name',
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='data',
            field=models.ImageField(upload_to='apps/images/'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='maxResult',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
